//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace 鑽礦遊戲2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("鑽礦遊戲2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture\Station\Gas Station\
        ///[Labels]
        ///6
        ///Station Location
        ///Exterior
        ///Panel
        ///Load Images
        ///Images On Panel
        ///Buttons
        ///
        ///[Station Location]
        ///20
        ///
        ///[Exterior]
        ///Exterior.png
        ///
        ///[Panel]
        ///Panel.png
        ///
        ///[Load Images]
        ///6
        ///Empty Tank.png
        ///Empty Tank
        ///Full Tank.png
        ///Full Tank
        ///Your Budget.png
        ///Your Budget
        ///Fill Tank Cost.png
        ///Fill Tank Cost
        ///Number Monitor\Panel.png
        ///Number Panel
        ///Number Monitor\Numbers.png
        ///Numbers
        ///
        ///[Images On Panel]
        ///5
        ///Empty Tank
        ///(25,25)
        ///Your Budget
        ///(175,25)
        ///Number Panel
        ///(175,100)
        ///Fill Tank [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GasStationLayoutSettings {
            get {
                return ResourceManager.GetString("GasStationLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GoodBye {
            get {
                object obj = ResourceManager.GetObject("GoodBye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, Hope You Like this Game
        ///I&apos;m the Creator, Thanks for Playing :)
        ///Name : 余柏序(Burney)
        ///Email : fsps60312@yahoo.com.tw
        ///Cellphone : 0919508359
        ///Facebook : https://www.facebook.com/fsps60312
        ///Description : Student on Information Section of Science Class 324 in Kaohsiung Senior High School
        ///Please Visit Our Fans Page at : https://www.facebook.com/KSHS105.Mobius
        ///Don&apos;t Worry, Information has Copied to Clipboard
        ///***All Rights Reserved***.
        /// </summary>
        internal static string GoodByeInformation {
            get {
                return ResourceManager.GetString("GoodByeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture\Station\Grocery Store\
        ///[Labels]
        ///6
        ///Station Location
        ///Exterior
        ///Panel
        ///Load Images
        ///Images On Panel
        ///Buttons
        ///
        ///[Station Location]
        ///80
        ///
        ///[Exterior]
        ///Exterior.png
        ///
        ///[Panel]
        ///Panel.png
        ///
        ///[Load Images]
        ///6
        ///Layout Rectangle.png
        ///Layout Rectangle
        ///Items\Small Dynamic.png
        ///Small Dynamic
        ///Items\Big Dynamic.png
        ///Big Dynamic
        ///Items\Barrel.png
        ///Barrel
        ///Items\First Aid.png
        ///First Aid
        ///Items\Any Door.png
        ///Any Door
        ///
        ///[Images On Panel]
        ///1
        ///Layout Rectangle
        ///(50,60)
        ///
        ///[Buttons]
        ///3
        ///Page Up
        ///(50,375)
        ///(200,50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GroceryStoreLayoutSettings {
            get {
                return ResourceManager.GetString("GroceryStoreLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture\Station\Maintenance Plant\
        ///[Labels]
        ///6
        ///Station Location
        ///Exterior
        ///Panel
        ///Load Images
        ///Images On Panel
        ///Buttons
        ///
        ///[Station Location]
        ///50
        ///
        ///[Exterior]
        ///Exterior.png
        ///
        ///[Panel]
        ///Panel.png
        ///
        ///[Load Images]
        ///2
        ///Gear\Background.png
        ///GearB
        ///Gear\Outline.png
        ///GearO
        ///
        ///[Images On Panel]
        ///0
        ///
        ///[Buttons]
        ///5
        ///$25
        ///(450,25)
        ///(225,50)
        ///$50
        ///(450,100)
        ///(225,50)
        ///$100
        ///(450,175)
        ///(225,50)
        ///Full\r\nRepair
        ///(450,250)
        ///(225,100)
        ///Exit
        ///(450,375)
        ///(225,50)
        ///
        ///.
        /// </summary>
        internal static string MaintenancePlantLayoutSettings {
            get {
                return ResourceManager.GetString("MaintenancePlantLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture\Station\Ore Processing Zone\
        ///[Labels]
        ///7
        ///Station Location
        ///Exterior
        ///Panel
        ///Load Images
        ///Images On Panel
        ///Buttons
        ///Fume Locations
        ///
        ///[Station Location]
        ///35
        ///
        ///[Exterior]
        ///Exterior.png
        ///
        ///[Panel]
        ///Panel.png
        ///
        ///[Load Images]
        ///2
        ///Layout Rectangle.png
        ///Layout Rectangle
        ///Today&apos;s Material Prices.png
        ///Caption
        ///
        ///[Images On Panel]
        ///2
        ///Caption
        ///(120,0)
        ///Layout Rectangle
        ///(50,60)
        ///
        ///[Buttons]
        ///4
        ///Pre
        ///(50,375)
        ///(100,50)
        ///Next
        ///(150,375)
        ///(100,50)
        ///Sell All
        ///(275,375)
        ///(175,50)
        ///Exit
        ///(475,375)
        ///(175,50)
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OreProcessingZoneLayoutSettings {
            get {
                return ResourceManager.GetString("OreProcessingZoneLayoutSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                
        ///       **      
        ///     **  **    
        ///   **      **  
        /// **  ******  **
        ///       **      
        ///  ************ 
        ///      ****     
        ///    ** ** **   
        ///  **   **   ** 
        ///               
        ///   **     **   
        ///   **    **    
        /// ****** *******
        ///   **   **   **
        ///  ****  **   **
        /// * ** * *******
        ///   **   **   **
        ///   **   **   **
        ///   **   *******
        ///               
        ///      **       
        ///  *************
        ///  ** ********* 
        ///  **   **  **  
        ///  ** **********
        ///  **     **  * 
        ///  **   * **    
        /// **     ***    
        /// *       **    
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheMap {
            get {
                return ResourceManager.GetString("TheMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture\Station\Upgrade Plant\
        ///[Labels]
        ///6
        ///Station Location
        ///Exterior
        ///Panel
        ///Load Images
        ///Images On Panel
        ///Buttons
        ///
        ///[Station Location]
        ///65
        ///
        ///[Exterior]
        ///Exterior.png
        ///
        ///[Panel]
        ///Panel.png
        ///
        ///[Load Images]
        ///45
        ///Engine\LV0.png
        ///Engine0
        ///Engine\LV1.png
        ///Engine1
        ///Engine\LV2.png
        ///Engine2
        ///Engine\LV3.png
        ///Engine3
        ///Engine\LV4.png
        ///Engine4
        ///Engine\LV5.png
        ///Engine5
        ///Engine\LV6.png
        ///Engine6
        ///Engine\LV7.png
        ///Engine7
        ///Engine\LV8.png
        ///Engine8
        ///Drill\LV0.png
        ///Drill0
        ///Drill\LV1.png
        ///Drill1
        ///Drill\LV2.png
        ///Drill2
        ///Dr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpgradePlantLayoutSettings {
            get {
                return ResourceManager.GetString("UpgradePlantLayoutSettings", resourceCulture);
            }
        }
    }
}
